# Generated by Django 5.0.7 on 2024-08-19 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.AutoField(primary_key=True, serialize=False)),
                ('estado_enum_ocupada_disponible_field', models.CharField(db_column="Estado ENUM('ocupada', 'disponible')", max_length=45)),
            ],
        ),
    ]
