# Generated by Django 5.0.7 on 2024-08-20 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='id_restaurante',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cantidadMesas', to='restaurantes.corp'),
        ),
        migrations.AlterField(
            model_name='mesa',
            name='estado_enum_ocupada_disponible_field',
            field=models.CharField(db_column="Estado ENUM('ocupada', 'disponible')", default='disponible', max_length=45),
        ),
    ]
