# Generated by Django 5.0.7 on 2024-08-24 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0004_mesa_id_mozo_and_more'),
        ('usuarios', '0002_usuarios_id_restaurante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mesa',
            name='id_mozo',
            field=models.ForeignKey(db_column='id_mozo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios'),
        ),
    ]
