# Generated by Django 5.0.7 on 2024-08-26 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0005_alter_mesa_id_mozo'),
        ('pedidos', '0006_rename_estado_pedido_pedidos_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidos'),
        ),
    ]
