# Generated by Django 5.0.7 on 2024-08-24 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0001_initial'),
        ('restaurantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alimentos',
            old_name='id_alimentos',
            new_name='id',
        ),
        migrations.AddField(
            model_name='alimentos',
            name='id_restaurante',
            field=models.ForeignKey(db_column='id_restaurante', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.corp'),
        ),
    ]
