# Generated by Django 5.0.7 on 2024-08-20 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caja', '0001_initial'),
        ('ordenes', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='id_ordenes',
            field=models.ForeignKey(db_column='id_ordenes', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='ordenes.ordenes'),
        ),
        migrations.AddField(
            model_name='caja',
            name='id_pedido',
            field=models.ForeignKey(blank=True, db_column='id_pedido', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidos'),
        ),
    ]
