# Generated by Django 5.0.7 on 2024-08-23 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurantes', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='id_restaurante',
            field=models.ForeignKey(db_column='id_restaurante', null=True, on_delete=django.db.models.deletion.CASCADE, to='restaurantes.corp'),
        ),
    ]
