# Generated by Django 5.0.7 on 2024-08-19 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cargos',
            fields=[
                ('id_cargos', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(db_column='Cargo', max_length=45)),
            ],
        ),
    ]
