# Generated by Django 5.0.7 on 2024-08-19 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('alimentos', '0001_initial'),
        ('bebidas', '0001_initial'),
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ordenes',
            fields=[
                ('id_ordenes', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.IntegerField(db_column='Cantidad')),
                ('precio', models.DecimalField(db_column='Precio', decimal_places=2, max_digits=10)),
                ('id_alimentos', models.ForeignKey(db_column='id_alimentos', on_delete=django.db.models.deletion.DO_NOTHING, to='alimentos.alimentos')),
                ('id_bebidas', models.ForeignKey(db_column='id_bebidas', on_delete=django.db.models.deletion.DO_NOTHING, to='bebidas.bebidas')),
                ('id_pedidos', models.ForeignKey(db_column='id_pedidos', on_delete=django.db.models.deletion.DO_NOTHING, to='pedidos.pedidos')),
            ],
        ),
    ]
