# Generated by Django 5.0.7 on 2024-08-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0002_alter_ordenes_cantidad_alter_ordenes_precio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenes',
            old_name='id_ordenes',
            new_name='id',
        ),
    ]
