# Generated by Django 5.0.7 on 2024-08-25 00:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_rename_id_alimentos_alimentos_id_and_more'),
        ('bebidas', '0002_rename_id_bebidas_bebidas_id_bebidas_id_restaurante'),
        ('ordenes', '0004_alter_ordenes_id_pedidos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='id_alimentos',
            field=models.ForeignKey(db_column='id_alimentos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alimentos.alimentos'),
        ),
        migrations.AlterField(
            model_name='ordenes',
            name='id_bebidas',
            field=models.ForeignKey(db_column='id_bebidas', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bebidas.bebidas'),
        ),
    ]
