# Generated by Django 5.0.7 on 2024-08-25 18:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alimentos', '0002_rename_id_alimentos_alimentos_id_and_more'),
        ('bebidas', '0002_rename_id_bebidas_bebidas_id_bebidas_id_restaurante'),
        ('ordenes', '0005_alter_ordenes_id_alimentos_alter_ordenes_id_bebidas'),
        ('pedidos', '0005_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='id_alimentos',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='id_bebidas',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='id_pedidos',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='id_alimento',
            field=models.ForeignKey(db_column='id_alimento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='alimentos.alimentos'),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='id_bebida',
            field=models.ForeignKey(db_column='id_bebida', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bebidas.bebidas'),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='id_pedido',
            field=models.ForeignKey(db_column='id_pedido', null=True, on_delete=django.db.models.deletion.CASCADE, to='pedidos.pedidos'),
        ),
    ]
