# Generated by Django 5.0.7 on 2024-08-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0006_remove_ordenes_id_alimentos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenes',
            name='id_alimento',
        ),
        migrations.RemoveField(
            model_name='ordenes',
            name='id_bebida',
        ),
        migrations.AddField(
            model_name='ordenes',
            name='alimento',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='bebida',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='ordenes',
            name='otros',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
    ]
