# Generated by Django 5.0.7 on 2024-08-26 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0007_remove_ordenes_id_alimento_remove_ordenes_id_bebida_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenes',
            name='otros',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
