# Generated by Django 5.0.7 on 2024-08-19 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id_pedidos', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField(db_column='Fecha_hora')),
                ('estado_pedido', models.CharField(blank=True, db_column='Estado_pedido', max_length=10, null=True)),
            ],
        ),
    ]
