# Generated by Django 5.0.7 on 2024-08-20 00:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0001_initial'),
        ('pedidos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidos',
            name='id_mesa',
            field=models.ForeignKey(db_column='id_mesa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mesa.mesa'),
        ),
        migrations.AddField(
            model_name='pedidos',
            name='id_usuario',
            field=models.ForeignKey(db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='usuarios.usuarios'),
        ),
    ]
