# Generated by Django 5.0.7 on 2024-08-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedidos_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='estado_pedido',
            field=models.CharField(blank=True, db_column='estado', max_length=10, null=True),
        ),
    ]
