# Generated by Django 5.0.7 on 2024-08-25 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_pedidos_estado_pedido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedidos',
            old_name='estado_pedido',
            new_name='estado',
        ),
        migrations.RemoveField(
            model_name='pedidos',
            name='numero_pedido',
        ),
    ]
