# Generated by Django 5.0.7 on 2024-08-26 16:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mesa', '0008_alter_mesa_id_pedido'),
        ('pedidos', '0007_alter_pedidos_id_mesa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedidos',
            name='id_mesa',
            field=models.ForeignKey(db_column='id_mesa', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='mesa.mesa'),
        ),
    ]
